/**
 * Catch all exception generated by async/await
 * @param {Function} fn
 * @returns Function
 */
export default (fn) => (req, res, next) => {
  fn(req, res, next).catch(next);
};
